---
- name: Configure UFW Firewall
  hosts: localhost
  become: yes

  tasks:

    - name: Install ufw package
      package:
        name: ufw
        state: present

    - name: Allow OpenSSH through UFW
      ufw:
        rule: allow
        name: OpenSSH

    - name: Enable the UFW firewall
      ufw:
        state: enabled

    - name: Check the status of the UFW firewall
      command: ufw status
      register: ufw_status

    - name: Display UFW status
      debug:
        var: ufw_status.stdout