---
- name: Add a new user on the local machine and set up SSH key
  hosts: localhost
  become: yes

  vars:
    # Load the SSH public key
    public_key: "{{ lookup('file', '../files/public_key.txt') }}"

    # Load the hashed user password. To generate use: ./scripts/hash-password.sh
    password_hash: "{{ lookup('file', '../files/password_hash.txt') }}"

  tasks:

    - name: Ansible username
      debug:
        msg: "Ansible username: {{ ansible_user }}"

    - name: Ensure the user is present
      user:
        name: "{{ ansible_user }}"
        state: present
        shell: /bin/bash
        groups: sudo
        password: "{{ password_hash }}"

    - name: Install sudo package
      package:
        name: sudo
        state: present

    - name: Display sudo password setting
      debug:
        msg: "Allow sudo without passowrd: {{ sudo_no_password }}"

    - name: Allow user to sudo
      lineinfile:
        path: /etc/sudoers
        line: "{{ ansible_user }} ALL=(ALL){{ ' NOPASSWD:' * sudo_no_password }} ALL"
        validate: 'visudo -cf %s'

    - name: Create .ssh directory for the new user
      file:
        path: "/home/{{ ansible_user }}/.ssh"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0700'

    - name: Add public key to authorized_keys
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ public_key }}"